services:
  app:
    image: ghcr.io/serafuku/neo-quesdon:${NEO_QUESDON_VERSION:-latest}
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - internal_network
      - external_network
    env_file:
      - ./config/docker.env
    links:
      - db
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - ./config/docker.env
    networks:
      - internal_network
    volumes:
      - redis:/data

  db:
    image: postgres:15-alpine
    restart: always
    networks:
      - internal_network
    env_file:
      - ./config/docker.env
    volumes:
      - db:/var/lib/postgresql/data

  bullboard:
    image: venatum/bull-board:latest
    ports:
      - "127.0.0.1:8090:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - internal_network
      - external_network
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  db:
  redis:

networks:
  internal_network:
    internal: true
  external_network:
