name: Build and push docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'develop'
    tags:
      - 'v**'
  release:
    types: [published, released, edited]
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          cache-from: type=registry,ref=${{env.REGISTRY}}/${{env.IMAGE_NAME}}:build-cache
          cache-to: type=registry,ref=${{env.REGISTRY}}/${{env.IMAGE_NAME}}:build-cache,mode=max,image-manifest=true,oci-mediatypes=true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
